Block using `--base-url` with `--root-dir` and suggest alternative
I want to make changes to these options so that they interact more
sensibly. I want this to happen in stages so that it's easier to review
and discuss, but each stage might change the behaviour of `--base-url`
and `--root-dir`.

I don't want users who might be using these options to discover that
it's changed and then adapt to the new behaviour, only for it to be
changed again later. I'd like it to all be locked down until we finish
the changes we want to make, and then we can present it as a polished
new feature with a well-defined behaviour.

Given the bugs currently in these options (base-url in particular),
I don't think anyone is using these flags together.

Github code search turns up only one YML file which is using this
combination of options:
https://github.com/search?q=%22--base-url%22+%22--root-dir%22+lychee+language%3AYML&type=code

The error message is:

> Error: Using root-dir and base-url together is not (yet) supported.
> Hint: In most cases, root-dir is sufficient and base-url should be
> removed. If you need to map a remote URL into a local folder, see
> https://lychee.cli.rs/recipes/local-folder/

TODO: update website!!!!

Possible issues:
- The example TOML file has all options defined. This change means that
  trying to use the example TOML config will fail. I don't know if
  there's a good way around this.