Report input source errors rather than tokio panics (#2074)
* Report input source errors rather than tokio panics

for example:
```
cargo run -- https://google.com https://fdsjaifjdsaoi.invalid
```

before:
```
thread 'tokio-runtime-worker' (74220) panicked at lychee-bin/src/commands/check.rs:337:18:
response channel closed: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Task failed to execute to completion

Caused by:
    task 28 panicked with message "response channel closed: SendError { .. }"
```
note that the real error isn't printed at all, because it's meant to be
returned to main and doesn't panic.

after:
```
Error: Network error: Connection failed. Check network connectivity and firewall settings (error sending request for url (https://fdsjaifjdsaoi.invalid/))

Caused by:
    0: error sending request for url (https://fdsjaifjdsaoi.invalid/)
    1: client error (Connect)
    2: dns error
    3: failed to lookup address information: Name or service not known
```
note also that this is not a panic

---------

Co-authored-by: Thomas Zahner <thomas.zahner@protonmail.ch>